name: Publish

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'yarn'

      - name: Install Yarn from corepack
        run: |
          corepack enable
          corepack prepare yarn@4.12.0 --activate

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Check Types
        run: yarn types:check

      - name: Run Tests
        run: yarn test

      - name: Lint Codebase
        run: yarn lint

      - name: Check Code Formatting
        run: yarn format:check

      - name: Build
        run: |
          yarn build
          test -f "dist/cjs/index.js"
          test -f "dist/esm/index.js"
          test -f "dist/types/index.d.ts"

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
